version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres:13-alpine
    volumes:      
      - ./data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_VENDOR=postgres
      - PGDATA=/var/lib/postgresql/data
    restart: always
    
  backend:
    build: 
      context: .
      dockerfile: dockerfiles/dev/fastapi/Dockerfile
    container_name: backend
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./src:/user/src
    env_file:
    - envs/dev/fastapi/.env
    ports:
      - "8000:80"
    depends_on:
      - db

