"""empty message

Revision ID: dda127c2c99d
Revises: 2dd28742b03b
Create Date: 2023-05-01 03:10:17.797166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda127c2c99d'
down_revision = '2dd28742b03b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_published')
    op.drop_column('posts', 'modified_at')
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
